name       : python-pyxattr
version    : 0.8.0
release    : 6
source     :
    - https://github.com/iustin/pyxattr/releases/download/v0.8.0/pyxattr-0.8.0.tar.gz : 7bf40cec5ae93dd656128717dbd268cfc3b3b28d95536d7886776c94fa267855
homepage   : https://github.com/iustin/pyxattr
license    : LGPL-2.1-or-later
component  : programming.python
summary    : A python module for accessing filesystem extended attributes
description: |
    pyxattr is a Python extension module which gives access to the extended attributes for filesystem objects available in some operating systems.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
