name       : python-pyxattr
version    : 0.6.1
release    : 1
source     :
    - https://github.com/iustin/pyxattr/archive/pyxattr-v0.6.1.tar.gz : 6bc782caabddb662929a76fffb8e5c9e80c131eca2405c954d394b4df3c4dec6
license    : LGPL-2.1-or-later
component  : programming.python
summary    : A python module for accessing filesystem extended attributes
description: |
    pyxattr is a Python extension module which gives access to the extended attributes for filesystem objects available in some operating systems.
builddeps  : 
    - python-sphinx
build      : |
    %python_setup
install    : |
    %python_install
