name       : python-pyxattr
version    : 0.7.2
release    : 2
source     :
    - https://github.com/iustin/pyxattr/releases/download/v0.7.2/pyxattr-0.7.2.tar.gz : 68477027e6d3310669f98aaef15393bfcd9b2823d7a7f00a6f1d91a3c971ae64
homepage   : https://github.com/iustin/pyxattr
license    : LGPL-2.1-or-later
component  : programming.python
summary    : A python module for accessing filesystem extended attributes
description: |
    pyxattr is a Python extension module which gives access to the extended attributes for filesystem objects available in some operating systems.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
